up:
  - node:
      version: v14.16.0
  - yarn_install
  - go:
      version: 1.21.4
      modules: true

test:
  run: go test ./... && go test -race ./...

benchmark:
  run: go test ./... -bench

build:
  run: go build ./...
