up:
  - node:
      version: v14.16.0
  - homebrew:
    - golangci/tap/golangci-lint
  - go:
      version: 1.16.3
      modules: true

test:
  run: go test ./... && go test -race ./...

build:
  run: go build -o get-repo-images ./src
