up:
  - node:
      version: v14.16.0
  - go:
      version: 1.16.3
      modules: true

test:
  run: go test ./... && go test -race ./...

benchmark:
  run: go test ./... -bench

build:
  run: go build -o get-repo-images ./src
