name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go test ./...
      - run: go test -race ./...
